### ISSUE TITLE
Clarify GitHub README

### ISSUE THREAD

**Issue by J00MZ** [avrahamcool/Aleph1#2]
Clarify GitHub README file to elaborate on:
- Project objective
- Installation instructions
- Dependencies

**Comment by avrahamcool** [comment]
hi @J00MZ ,
I'd like you to revise the readme.
do you think it has sufficient explanation?
where should I elaborate more?

although.. the formatting is so bad - even after I improved it..
can you give me a hand?

**Comment by J00MZ** [comment]
Sure. Will do

**Comment by avrahamcool** [comment]
so, can be closed?

**Comment by avrahamcool** [comment]
I think it's pretty clear now..
